name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  lint: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Super-Linter
      uses: super-linter/super-linter@v5.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: Reports
        OUTPUT_DETAILS: detailed
          
