name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  lint: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Vale
      uses: errata-ai/vale-action@2.1.0
      with:
        debug: true
        styles: 
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
